/*
 * This file is generated by jOOQ.
 */
package br.com.renanschmitt.medium.db;


import br.com.renanschmitt.medium.db.tables.Persons;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.persons</code>.
     */
    public final Persons PERSONS = Persons.PERSONS;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Persons.PERSONS
        );
    }
}
