/*
 * This file is generated by jOOQ.
 */
package br.com.renanschmitt.medium.db;


import br.com.renanschmitt.medium.db.tables.Persons;
import br.com.renanschmitt.medium.db.tables.records.PersonsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PersonsRecord> KEY_PERSONS_PRIMARY = Internal.createUniqueKey(Persons.PERSONS, DSL.name("KEY_persons_PRIMARY"), new TableField[] { Persons.PERSONS.ID }, true);
}
