/*
 * This file is generated by jOOQ.
 */
package br.com.renanschmitt.medium.db;


import br.com.renanschmitt.medium.db.tables.Persons;


/**
 * Convenience access to all tables in jooq.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.persons</code>.
     */
    public static final Persons PERSONS = Persons.PERSONS;
}
