/*
 * This file is generated by jOOQ.
 */
package br.com.renanschmitt.medium.db.tables.pojos;

import java.io.Serializable;
import java.time.LocalDate;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PersonsPojo implements Serializable {

  private static final long serialVersionUID = 1L;

  private Long id;
  private String name;
  private LocalDate birthDate;

  public PersonsPojo() {}

  public PersonsPojo(PersonsPojo value) {
    this.id = value.id;
    this.name = value.name;
    this.birthDate = value.birthDate;
  }

  public PersonsPojo(Long id, String name, LocalDate birthDate) {
    this.id = id;
    this.name = name;
    this.birthDate = birthDate;
  }

  /** Getter for <code>jooq.persons.id</code>. */
  public Long getId() {
    return this.id;
  }

  /** Setter for <code>jooq.persons.id</code>. */
  public void setId(Long id) {
    this.id = id;
  }

  /** Getter for <code>jooq.persons.name</code>. */
  public String getName() {
    return this.name;
  }

  /** Setter for <code>jooq.persons.name</code>. */
  public void setName(String name) {
    this.name = name;
  }

  /** Getter for <code>jooq.persons.birth_date</code>. */
  public LocalDate getBirthDate() {
    return this.birthDate;
  }

  /** Setter for <code>jooq.persons.birth_date</code>. */
  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (obj == null) return false;
    if (getClass() != obj.getClass()) return false;
    final PersonsPojo other = (PersonsPojo) obj;
    if (this.id == null) {
      if (other.id != null) return false;
    } else if (!this.id.equals(other.id)) return false;
    if (this.name == null) {
      if (other.name != null) return false;
    } else if (!this.name.equals(other.name)) return false;
    if (this.birthDate == null) {
      if (other.birthDate != null) return false;
    } else if (!this.birthDate.equals(other.birthDate)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
    result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
    result = prime * result + ((this.birthDate == null) ? 0 : this.birthDate.hashCode());
    return result;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Persons (");

    sb.append(id);
    sb.append(", ").append(name);
    sb.append(", ").append(birthDate);

    sb.append(")");
    return sb.toString();
  }
}
